### ISSUE TITLE
1.20.4 incompatibility ?

### ISSUE THREAD

**Issue by ykvox** [Superkat32/PostmortalParticles#6]
hii ! 
i'm getting a crash updating the mod to 1.20.4, linking report here:

https://mclo.gs/4Fl53dm

have a good day !

**Comment by Superkat32** [comment]
It seems like you may have the wrong version of YACL? 

Maybe try installing the version specifically for 1.20.4???
https://modrinth.com/mod/yacl/version/3.3.2+1.20.4-fabric

**Comment by ykvox** [comment]
wow thanks for the quick response !
it was indeed the wrong version, thanks a lot ! :)

**Comment by Superkat32** [comment]
No worries!
